//for in loop
// const JSON = {
//     "name" : "Maheshkumar A",
//     "age"  : "23",
//     "city" : "Coimbatore",
//     "role" : "fsd-developer",
// }

// for(var key in JSON){
//     console.log(key+":"+JSON[key])
    //console.log(JSON["name"])
//}

//for each loop
// let jsonArray = [
//     {"name": "siva", "age": 23},
//     {"name": "kaushik", "age": 24},
//     {"name": "ram", "age": 22}
//    ];
   
//    jsonArray.forEach((item)=>{
//     console.log("name: "+ item.name)
//    })

//for loop
//    const JSONfor = {
//     "name" : "Maheshkumar A",
//     "age"  : "23",
//     "city" : "Coimbatore",
//     "role" : "fsd-developer",
// }
// var obj = Object.keys(JSONfor);

// for(i=0;i<obj.length;i++){
//     var key =obj[i];
//     var value = JSONfor[key];
//     console.log(`${key}:${value}`)
// }

//for of
// const JSONfor = {
//     "name" : "Maheshkumar A",
//     "age"  : "23",
//     "city" : "Coimbatore",
//     "role" : "fsd-developer",
// };
// var person = Object.entries(JSONfor);

// for (const [key, value] of person) {
//     console.log(`${key}: ${value}`);
// }








